package WXUtils.java;


/**
 * 文档编码
 */
public enum StatusCode {

  SUCESS(200, "Success", ""),
  SUCESSLAYUI(0, "Success", ""),
  SUCESSWECHAT(0, "Success", ""),
  NOTFOUND(404, "", ""),
  FAILUER(901, "Failur", ""),
  SESSION_TIMEOUT(902, "SESSION_TIMEOUT", ""),
  SYSTEM_ERROR(900, "SYSTEM_ERROR", ""),
  SYSTEM_ILLEGAL(903, "SYSTEM_ILLEGAL", ""),
  DATA_NOT_EXISTS(706, "DATA_NOT_EXISTS", ""),
  DATA_IS_EXISTS(707, "DATA_IS_EXISTS", ""),
  DATA_NOT_MATCH(708, "DATA_NOT_MATCH", ""),

  SKU_IS_EXISTS(707, "SKU_IS_EXISTS", ""),
  SHOP_ID_NOT_EXISTS(717, "SHOP_ID_NOT_EXISTS", ""),
  MISSING_PARAMETER_ERROR(701, "MISSING_PARAMETER_ERROR", ""),
  USER_LOGIN_ERROR(702, "USER_LOGIN_ERROR", ""),
  USER_DOES_NOT_EXIST(703, "USER_DOES_NOT_EXIST", ""),
  NO_PERMISSION_ERROR(704, "NO_PERMISSION_ERROR", ""),
  PARAMETER_FORMATE_RROR(705, "PARAMETER_FORMATE_RROR", ""),
  PASSWORD_DIFFERENT(706, "PASSWORD_DIFFERENT", ""),
  OLDPASSWORD_RROR(709, "OLDPASSWORD_RROR", ""),
  USER_EXIST_RROR(710, "USER_EXIST_RROR", ""),
  API_FREQUENTLY_ERROR(711, "API_FREQUENTLY_ERROR", ""),
  PICTURE_FORMAT_ERROR(712, "PICTURE_FORMAT_ERROR", ""),
  TIME_FORMAT_ERROR(713, "TIME_FORMAT_ERROR", ""),
  CREDITAMOUNT_ERROR(714, "CREDITAMOUNT_ERROR", ""),
  PUSH_DATA_FAILURE(715, "PUSH_DATA_FAILURE", ""),
  ORDER_TYPE_FAILURE(716, "ORDER_TYPE_FAILURE", ""),
  ORDERID_NOT_EXIST(717, "ORDERID_NOT_EXIST", ""),
  DEPT_HAS_CHILD_DELETE_ERROR(801, "DEPT_HAS_CHILD_DELETE_ERROR", ""),
  DEPT_HAS_USER_DELETE_ERROR(802, "DEPT_HAS_USER_DELETE_ERROR", ""),
  RULID_NOT_FIND_ERROR(803, "RULID_NOT_FIND_ERROR", ""),
  DELETE_ERROR(804, "DELETE_ERROR", ""),


  SHOPSALE_ERROR_BIND(741,"SHOPSALE_ERROR_BIND",""),
  SHOPSALE_ERROR_MOREBIND(742,"SHOPSALE_ERROR_MOREBIND",""),
  SHOPSALE_MISSING_PARAMETER_ERROR(743,"SHOPSALE_MISSING_PARAMETER_ERROR",""),
  SHOPSALE_CREATE_ERROR(744,"SHOPSALE_CREATE_ERROR",""),
  SHOPSALE_CATEGORYCREATE_ERROR(745,"SHOPSALE_CATEGORYCREATE_ERROR",""),
  MONTH_MAXDAY_ERROR(746,"MONTH_MAXDAY_ERROR",""),
  SHOPSALE_CREATEANDUPDATE_ERROR(747,"SHOPSALE_CREATEANDUPDATE_ERROR",""),
  SHOPSALE_CATEGORYCREATECREATEANDUPDATE_ERROR(748,"SHOPSALE_CATEGORYCREATECREATEANDUPDATE_ERROR",""),
  SHOPSALE_ISFIRSTDAYOFMONTH_ERROR(749,"SHOPSALE_ISFIRSTDAYOFMONTH_ERROR",""),


  RPSHOP_DAILY_SALSES_ERROR(750,"RPSHOP_DAILY_SALSES_ERROR",""),
  //鍗�?�埜閿欒�?
  COUPON_ERROR_NOCOUPON(601,"COUPON_ERROR_NOCOUPON",""),
  COUPON_ERROR_USABLE(602,"COUPON_ERROR_USABLE",""),
  COUPON_ERROR_EXPIRED(603,"COUPON_ERROR_EXPIRED",""),
  COUPON_ERROR_ISSUECHANNEL(604,"COUPON_ERROR_ISSUECHANNEL",""),
  COUPON_ERROR_COUPONTYPE(605,"COUPON_ERROR_COUPONTYPE",""),
  COUPON_ERROR_ERCOUPON(606,"COUPON_ERROR_ERCOUPON",""),
  COUPON_ERROR_COUPONSHOP(607,"COUPON_ERROR_COUPONSHOP",""),
  COUPON_ERROR_COUPONGOODS(608,"COUPON_ERROR_COUPONGOODS",""),
  COUPON_ERROR_VIP(609,"COUPON_ERROR_VIP",""),
  COUPON_ERROR_USERVIP(610,"COUPON_ERROR_USERVIP",""),
  COUPON_ERROR_OVERAMOUNT(611,"COUPON_ERROR_OVERAMOUNT",""),
  COUPON_ERROR_DELETECOUPON(612,"COUPON_ERROR_DELETECOUPON",""),
  COUPON_ERROR_NOQRCODEURL(613,"COUPON_ERROR_NOQRCODEURL",""),
  COUPON_ERROR_TIMENOTREADY(614,"COUPON_ERROR_TIMENOTREADY","");

  /**
   * 杩斿洖鐮�?
   */
  private int code;

  /**
   * 淇℃�?
   */
  private String errorMsg;

  /**
   * 璇存�?
   */
  private String remark;

  private StatusCode(int code, String errorMsg, String remark) {
    this.code = code;
    this.errorMsg = errorMsg;
    this.remark = remark;
  }


  public int getCode() {
    return code;
  }

  public void setCode(int code) {
    this.code = code;
  }

  public String getErrorMsg() {
    return errorMsg;
  }

  public void setErrorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
  }

  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

}
